/**
 * React Icons
 * see: https://react-icons.github.io/react-icons/
 */
//  export const iconList = [
// <svg width="24" height="24" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" role="img" aria-hidden="true" focusable="false"><path d="M19 3H5c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2zM5 4.5h14c.3 0 .5.2.5.5v8.4l-3-2.9c-.3-.3-.8-.3-1 0L11.9 14 9 12c-.3-.2-.6-.2-.8 0l-3.6 2.6V5c-.1-.3.1-.5.4-.5zm14 15H5c-.3 0-.5-.2-.5-.5v-2.4l4.1-3 3 1.9c.3.2.7.2.9-.1L16 12l3.5 3.4V19c0 .3-.2.5-.5.5z"></path></svg>

// Font Awesome
export const faIcons = [
	// Animals / 自然
	'fa-solid fa-earth-asia',
	'fa-solid fa-globe',
	'fa-solid fa-moon',

	// map
	'fa-regular fa-compass',
	'fa-regular fa-map',
	'fa-solid fa-map-location-dot',
	'fa-solid fa-location-pin',
	'fa-solid fa-location-arrow',

	// Alert
	'fa-solid fa-bell',
	'fa-solid fa-question',
	'fa-solid fa-circle-question',
	'fa-regular fa-circle-question',
	'fa-solid fa-exclamation',
	'fa-solid fa-triangle-exclamation',
	'fa-solid fa-circle-exclamation',

	// mark / shape
	'fa-solid fa-check',
	'fa-solid fa-circle-check',
	'fa-regular fa-circle-check',
	'fa-solid fa-plus',
	'fa-solid fa-minus',
	'fa-solid fa-xmark',
	'fa-regular fa-circle',
	'fa-regular fa-square',

	'fa-solid fa-bookmark',
	'fa-regular fa-bookmark',
	'fa-solid fa-star',
	'fa-regular fa-star',
	'fa-solid fa-heart',
	'fa-regular fa-heart',
	'fa-solid fa-lightbulb',
	'fa-regular fa-lightbulb',
	'fa-solid fa-clock',
	'fa-regular fa-clock',
	'fa-regular fa-calendar',
	'fa-solid fa-calendar-days',
	'fa-solid fa-lock',
	'fa-solid fa-unlock',
	'fa-solid fa-lock-open',
	'fa-solid fa-key',
	'fa-solid fa-gear',
	'fa-solid fa-gears',

	'fa-solid fa-thumbs-up',
	'fa-regular fa-thumbs-up',
	'fa-solid fa-thumbs-down',
	'fa-regular fa-thumbs-down',

	// person
	'fa-solid fa-user',
	'fa-regular fa-user',
	'fa-solid fa-user-plus',
	'fa-solid fa-user-group',
	'fa-solid fa-user-graduate',
	'fa-solid fa-user-tie',
	// 'fa-solid fa-address-book',
	// 'fa-regular fa-address-book',
	'fa-solid fa-address-card',
	'fa-regular fa-address-card',

	// 'fa-solid fa-eye',

	// Arrow
	'fa-solid fa-angle-down',
	'fa-solid fa-angle-left',
	'fa-solid fa-angle-right',
	'fa-solid fa-angle-up',
	'fa-solid fa-arrow-down',
	'fa-solid fa-arrow-left',
	'fa-solid fa-arrow-right',
	'fa-solid fa-arrow-up',
	'fa-solid fa-caret-down',
	'fa-solid fa-caret-left',
	'fa-solid fa-caret-right',
	'fa-solid fa-caret-up',
	'fa-solid fa-recycle',
	'fa-solid fa-share',
	'fa-solid fa-arrow-up-right-from-square',
	'fa-solid fa-download',
	'fa-solid fa-upload',
	'fa-solid fa-cloud-arrow-down',
	'fa-solid fa-cloud-arrow-up',

	// automotive
	'fa-solid fa-car',
	'fa-solid fa-bus',
	'fa-solid fa-train-subway',
	'fa-solid fa-ship',
	'fa-solid fa-truck',
	'fa-solid fa-motorcycle',
	'fa-solid fa-plane',

	// chart
	'fa-solid fa-chart-line',
	'fa-solid fa-chart-column',
	'fa-solid fa-chart-pie',
	'fa-solid fa-chart-simple',
	'fa-solid fa-diagram-project',

	// buildings
	'fa-solid fa-house',
	'fa-solid fa-building',
	'fa-regular fa-building',
	'fa-solid fa-school',
	'fa-solid fa-store',
	'fa-solid fa-tent',
	'fa-solid fa-campground',
	'fa-solid fa-torii-gate',
	'fa-solid fa-vihara',
	'fa-solid fa-archway',

	// pen
	'fa-solid fa-pen',
	'fa-solid fa-marker',
	'fa-solid fa-list-check',
	'fa-solid fa-paintbrush',
	'fa-solid fa-palette',
	// 'fa-solid fa-brush',
	// 'fa-solid fa-droplet',

	// business
	'fa-solid fa-paperclip',
	'fa-solid fa-note-sticky',
	'fa-solid fa-book',
	'fa-solid fa-briefcase',

	'fa-solid fa-envelope',
	'fa-regular fa-envelope',
	'fa-solid fa-phone',
	'fa-solid fa-phone-volume',
	'fa-solid fa-print',
	'fa-solid fa-file',
	'fa-regular fa-file',
	'fa-solid fa-folder',
	'fa-regular fa-folder',
	'fa-regular fa-folder-open',
	'fa-solid fa-folder-tree',
	'fa-solid fa-tag',
	'fa-solid fa-sitemap',
	'fa-solid fa-handshake',
	'fa-regular fa-handshake',
	// 'fa-solid fa-handshake-simple',

	// child

	// communitcation
	'fa-solid fa-comment',
	'fa-regular fa-comment',
	'fa-solid fa-comments',
	'fa-regular fa-comments',
	'fa-solid fa-message',
	'fa-regular fa-message',

	//device
	'fa-solid fa-computer',
	'fa-solid fa-display',
	// 'fa-solid fa-desktop',
	'fa-solid fa-laptop',
	// 'fa-solid fa-tablet',
	'fa-solid fa-tablet-screen-button',
	// 'fa-solid fa-mobile',
	'fa-solid fa-mobile-screen-button',
	'fa-regular fa-keyboard',
	'fa-solid fa-computer-mouse',
	// 'fa-solid fa-tv',
	'fa-solid fa-server',
	'fa-solid fa-database',
	// 'fa-solid fa-hard-drive',
	// 'fa-solid fa-microchip',
	// 'fa-solid fa-shield-halved',
	'fa-solid fa-wifi',
	'fa-brands fa-bluetooth',
	'fa-solid fa-code',
	'fa-solid fa-plug',
	// 'fa-solid fa-sd-card',
	// 'fa-solid fa-sim-card',

	// music / film / video / image
	'fa-solid fa-camera',
	// 'fa-solid fa-camera-retro',
	'fa-solid fa-video',
	'fa-solid fa-headphones',
	'fa-solid fa-headset',
	'fa-solid fa-microphone',

	'fa-solid fa-image',
	'fa-regular fa-image',
	'fa-solid fa-photo-film',
	'fa-solid fa-clapperboard',
	'fa-solid fa-music',

	//money
	'fa-solid fa-yen-sign',
	'fa-solid fa-dollar-sign',
	'fa-solid fa-bitcoin-sign',
	'fa-solid fa-money-bill-wave',
	'fa-solid fa-hand-holding-dollar',
	'fa-solid fa-sack-dollar',
	'fa-solid fa-coins',
	'fa-solid fa-piggy-bank',
	'fa-solid fa-wallet',
	'fa-solid fa-bag-shopping',
	'fa-solid fa-cart-shopping',
	'fa-solid fa-cart-arrow-down',
	'fa-solid fa-credit-card',
	'fa-regular fa-credit-card',

	// 'fa-brands fa-alipay',
	'fa-brands fa-apple-pay',
	'fa-brands fa-google-pay',
	'fa-brands fa-amazon-pay',
	'fa-brands fa-stripe',
	'fa-brands fa-paypal',
	'fa-brands fa-google-wallet',
	'fa-brands fa-cc-visa',
	'fa-brands fa-cc-mastercard',
	'fa-brands fa-cc-amex',
	'fa-brands fa-cc-jcb',
	// 'fa-brands fa-cc-paypal',
	// 'fa-brands fa-cc-stripe',
	// 'fa-brands fa-cc-amazon-pay',
	// 'fa-brands fa-cc-apple-pay',
	// "fa-brands fa-cc-diners-club",
	// "fa-brands fa-cc-discover",

	// その他カテゴリーで使えそうなやつなど
	'fa-solid fa-mug-saucer',
	'fa-solid fa-mug-hot',
	'fa-solid fa-wine-glass',
	'fa-solid fa-utensils',
	'fa-solid fa-smoking',
	'fa-solid fa-ban-smoking',
	'fa-solid fa-shirt',
	'fa-solid fa-glasses',
	'fa-solid fa-bed',
	'fa-solid fa-gift',
	'fa-solid fa-gem',
	'fa-solid fa-crown',
	'fa-solid fa-clover',
	'fa-solid fa-diamond',
	'fa-solid fa-baseball-bat-ball',
	'fa-solid fa-gamepad',
	'fa-solid fa-shapes',
	// 'fa-solid fa-robot',

	// 動物
	'fa-solid fa-cat',
	'fa-solid fa-dog',
	'fa-solid fa-dove',
	'fa-solid fa-feather',
	'fa-solid fa-fish',

	// 自然
	'fa-solid fa-apple-whole',
	'fa-solid fa-tree',
	'fa-solid fa-leaf',
	'fa-solid fa-fire',
	'fa-solid fa-water',
	'fa-solid fa-bolt',

	// baby / kids
	'fa-solid fa-baby',
	'fa-solid fa-child',
	'fa-solid fa-child-reaching',

	// Accessibility
	'fa-solid fa-universal-access',
	'fa-brands fa-accessible-icon',
	'fa-solid fa-wheelchair',
	// 'fa-solid fa-fingerprint',
	'fa-solid fa-person-cane',
	'fa-solid fa-person-walking-with-cane',
	'fa-solid fa-handshake-angle',

	// logo
	// 'fa-brands fa-youtube',
	// 'fa-brands fa-steam',
	// 'fa-brands fa-playstation',
	// 'fa-brands fa-twitch',
	// 'fa-brands fa-xbox',
	// 'fa-brands fa-unsplash',
];

// Ionicons 5
export const ioIcons = [
	// 'IoLogoIonic',

	//記号系
	'IoAlertCircle',
	'IoAlertCircleOutline',
	'IoHelpCircle',
	'IoHelpCircleOutline',
	'IoInformationCircle',
	'IoInformationCircleOutline',
	'IoWarning',
	'IoWarningOutline',
	'IoCheckbox',
	'IoCheckboxOutline',
	'IoCheckmarkCircle',
	'IoCheckmarkCircleOutline',
	'IoCheckmark',
	// IoList
	// IoListCircle
	// IoListCircleOutline

	// 図形
	'IoClose',
	'IoEllipse',
	'IoEllipseOutline',
	'IoTriangle',
	'IoTriangleOutline',
	'IoSquare',
	'IoSquareOutline',
	'IoHeart',
	'IoHeartOutline',
	'IoStar',
	'IoStarOutline',
	// 'IoStarHalf',

	//矢印系
	// 'IoArrowBackCircle',
	// 'IoArrowDownCircle',
	// 'IoArrowForwardCircle',
	// 'IoArrowUpCircle',
	'IoArrowBackCircleOutline',
	'IoArrowDownCircleOutline',
	'IoArrowForwardCircleOutline',
	'IoArrowUpCircleOutline',
	'IoArrowBack',
	'IoArrowDown',
	'IoArrowForward',
	'IoArrowUp',
	'IoArrowRedo',
	'IoArrowUndo',
	// 'IoArrowRedoOutline',
	// 'IoArrowUndoOutline',
	'IoCaretBack',
	'IoCaretDown',
	'IoCaretForward',
	'IoCaretUp',
	'IoChevronBack',
	'IoChevronDown',
	'IoChevronForward',
	'IoChevronUp',
	'IoEnterOutline',
	'IoExitOutline',
	'IoOpenOutline',

	//デバイス
	'IoDesktopSharp',
	'IoLaptopOutline',
	'IoTabletPortraitSharp',
	'IoPhonePortraitOutline',
	'IoQrCodeSharp',
	'IoRadioOutline',
	'IoWifi',
	'IoCodeSlash',
	'IoBatteryCharging',

	// 乗り物
	'IoAirplane',
	// 'IoAirplaneOutline',
	'IoBus',
	// 'IoBusOutline',
	'IoBoat',
	// 'IoBoatOutline',
	'IoCar',
	// 'IoCarOutline',
	'IoCarSport',
	// 'IoCarSportOutline',
	'IoSubway',
	'IoBicycle',

	// chart系
	'IoAnalytics',
	'IoCellular',
	'IoPieChart',
	'IoStatsChart',
	'IoBarChartSharp',
	'IoCalculatorSharp',

	// 自然系
	'IoEarth',
	'IoPlanet',
	'IoFlame',
	'IoWater',
	'IoFlash',
	'IoFlower',
	'IoLeaf',

	// 汎用性高そうなものは solid と outline
	'IoSettings',
	'IoSettingsOutline',
	'IoAlarm',
	'IoAlarmOutline',
	'IoBagHandle',
	'IoBagHandleOutline',
	'IoBook',
	'IoBookOutline',
	'IoBookmark',
	'IoBookmarkOutline',
	'IoBriefcase',
	'IoBriefcaseOutline',
	'IoBrush',
	'IoBrushOutline',
	'IoBuild',
	'IoBuildOutline',
	'IoBulb',
	'IoBulbOutline',
	'IoCalendar',
	'IoCalendarOutline',
	'IoCall',
	'IoCallOutline',
	'IoCart',
	'IoCartOutline',
	'IoChatbox',
	'IoChatboxOutline',
	'IoChatbubbleEllipses',
	'IoChatbubbleEllipsesOutline',
	'IoConstruct',
	'IoConstructOutline',
	'IoCube',
	'IoCubeOutline',
	'IoTime',
	'IoTimeOutline',
	'IoImage',
	'IoImageOutline',
	'IoCamera',
	'IoCameraOutline',

	// outlineなどバリエーションないもの
	'IoAccessibility',
	'IoLocationSharp',
	'IoHome',
	'IoStorefront',
	'IoBusinessSharp',
	// 'IoAttach',
	// 'IoApps',
	'IoCalculatorSharp',
	'IoAperture',
	'IoCardOutline',

	'IoColorFill',
	'IoGameController',
	'IoGift',
	'IoGlasses',
	'IoGrid',
	// 'IoKey',
	'IoLayers',
	'IoLockClosed',
	'IoLockOpen',
	'IoMail',
	'IoMusicalNotes',
	'IoNotifications',
	'IoOptions',
	'IoPerson',
	'IoReceiptOutline',
	'IoSearch',
	'IoTrophy',
	'IoBarbell',
	'IoBed',
	'IoRestaurantSharp',
	'IoBeer',
	'IoCafe',
	'IoPencilSharp',
	'IoColorPalette',
	'IoDiamond',
	'IoHeadset',
	'IoPrint',
];

// Material Design icons
// export const mdIcons = [
// 	'Md3DRotation',
// 	'MdAccessibilityNew',
// 	'MdAccessibility',
// 	'MdAccessibleForward',
// 	'MdAccessible',
// 	'MdAccountBalanceWallet',
// 	'MdAccountBalance',
// 	'MdAccountBox',
// 	'MdAccountCircle',
// 	'MdAddShoppingCart',
// 	'MdAddTask',
// 	'MdAddToDrive',
// 	'MdAddchart',
// ];

// Feather icons
export const fiIcons = [
	// 'FiFeather',

	// マーク系
	// 'FiAlertOctagon',
	'FiCheck',
	'FiCircle',
	'FiX',
	'FiHeart',
	'FiHexagon',
	'FiHelpCircle',
	'FiInfo',
	'FiAlertCircle',
	'FiAlertTriangle',
	'FiSquare',
	'FiTriangle',
	'FiStar',

	// 矢印系
	'FiArrowDownCircle',
	'FiArrowDownCircle',
	'FiArrowLeftCircle',
	'FiArrowRightCircle',
	'FiArrowUpCircle',
	'FiArrowDown',
	'FiArrowLeft',
	'FiArrowRight',
	'FiArrowUp',
	'FiChevronDown',
	'FiChevronLeft',
	'FiChevronRight',
	'FiChevronUp',
	'FiExternalLink',
	'FiDownload',
	'FiLogIn',
	'FiLogOut',

	// デバイス系
	'FiTv',
	'FiMonitor',
	'FiTablet',
	'FiSmartphone',
	'FiMousePointer',
	'FiMusic',
	'FiCamera',
	'FiHeadphones',
	'FiCode',
	'FiDatabase',
	'FiHardDrive',
	'FiServer',
	'FiEdit2',

	'FiFilm',
	'FiFile',
	'FiFileText',
	'FiFolder',
	'FiLayers',
	'FiLayout',

	// その他
	'FiHome',
	'FiImage',
	'FiActivity',
	// 'FiAirplay',
	'FiAnchor',
	'FiAperture',
	'FiArchive',
	'FiAward',
	'FiBatteryCharging',
	// 'FiBattery',
	'FiBell',
	'FiBook',
	'FiBookmark',
	'FiBox',
	'FiBriefcase',
	'FiCalendar',
	'FiClock',
	'FiCoffee',
	'FiDroplet',
	'FiGift',
	'FiGrid',
	'FiLink',
	'FiLoader',
	'FiLock',
	'FiUnlock',
	'FiMail',
	'FiMapPin',
	'FiMap',
	'FiMessageSquare',
	'FiMessageCircle',
	'FiPackage',
	'FiPhone',
	'FiPieChart',
	'FiPrinter',
	'FiSearch',
	'FiSend',
	'FiSettings',
	'FiShoppingBag',
	'FiShoppingCart',
	'FiTag',
	'FiThumbsUp',
	'FiThumbsDown',
	'FiTool',
	'FiUser',
];

// Arkheアイコン
export const arkbIcons = [
	'arkb-svg-point',
	'arkb-svg-alert',
	'arkb-svg-warning',
	'arkb-svg-check',
	'arkb-svg-pen',
	'arkb-svg-megaphone',
	'arkb-svg-mail',
	'arkb-svg-cart',
	'arkb-svg-thumb_down',
	'arkb-svg-thumb_up',
	'arkb-svg-comment',
	'arkb-svg-home',
	'arkb-svg-person',
	'arkb-svg-star',
	'arkb-svg-heart',
	'arkb-svg-cog',
	'arkb-svg-quill',
	'arkb-svg-link',
	'arkb-svg-blocked',
	'arkb-svg-batsu',
];
